# Definición del trabajo de compilación
build:
  stage: build
  script:
    # Inicia el trabajo de compilación
    - npm install     # Instala las dependencias
    - npm run build   # Compila la aplicación

# Definición del trabajo de pruebas
test:
  stage: test
  script:
    # Inicia el trabajo de pruebas
    - npm run test    # Ejecuta las pruebas unitarias

# Definición del trabajo de despliegue a un entorno de liberación
release:
  stage: release
  script:
    # Inicia el despliegue en un entorno de liberación
    - echo "Desplegando en un entorno de liberación..."
    # Aquí podrías agregar los comandos necesarios para desplegar en un entorno de liberación,
    # como crear un nuevo entorno, configurar variables de entorno, etc.
  environment:
    name: release    # Nombre del entorno de liberación
    url: https://example.com  # URL del entorno de liberación (si es aplicable)
  only:
    - master         # Solo se ejecuta en la rama master

# Definición del trabajo de pruebas en el entorno de liberación
release_test:
  stage: test
  script:
    # Inicia las pruebas en el entorno de liberación
    - echo "Ejecutando pruebas en el entorno de liberación..."
    # Aquí podrías agregar los comandos necesarios para ejecutar pruebas específicas en el entorno de liberación
  environment:
    name: release    # Nombre del entorno de liberación
    url: https://example.com  # URL del entorno de liberación (si es aplicable)
  only:
    - master         # Solo se ejecuta en la rama master

# Definición del trabajo de despliegue a producción
deploy:
  stage: deploy
  script:
    # Inicia el despliegue a producción
    # Instalar la CLI de Vercel
    - npm install -g vercel
    # Autenticarse con Vercel utilizando el token de autenticación
    - vercel login --token $VERCEL_TOKEN
    # Desplegar la aplicación en Vercel
    - vercel --prod --confirm --token $VERCEL_TOKEN
  environment:
    name: production # Entorno de producción
  only:
    - master         # Solo se ejecuta en la rama master
